version: '3'
services:
  backend:
    build: .
    env_file: ./env
    volumes:
      - ./app/:/app
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: postgres:9.6.17
    environment:
      POSTGRES_PASSWORD: password